### ISSUE TITLE
Excel-Friendly default implementation

### ISSUE THREAD

**Issue by LostKobrakai** [dashbitco/nimble_csv#45]
I'm wondering if there could be an excel friendly default implementation besides `NimbleCSV.RFC4180` based on https://underthehood.meltwater.com/blog/2018/08/08/excel-friendly-csv-exports-with-elixir/.

This seems to be working fine for recent versions of Excel, Numbers, OpenOffice based on my quick research, while RFC4180 just produces garbage in Excel.

**Comment by josevalim** [comment]
We don't have plans to tackle it but a pull request is welcome. In particular, I think we can have the encoding option given when generating the parser/encoder, which should be more efficient. Recent Elixir versions can also automatically remove the BOM when working with file streams. Thanks!

**Comment by josevalim** [comment]
@LostKobrakai Can you please give master a try?

I have renamed the module to `NimbleCSV.Spreadsheet` and I have optimized the code a bit.

**Comment by LostKobrakai** [comment]
Looks great and seems to work fine on my side.

**Comment by LostKobrakai** [comment]
Not sure if it's worth it, but now there are two `@compile` module attributes to inline calls. Maybe those can/should be merged?

**Comment by josevalim** [comment]
I like to keep them close to where they are used. They are actually 3 calls, all of them are automatically merged. :)
