### ISSUE TITLE
make it work with use.

### ISSUE THREAD

**Issue by fcevado** [dashbitco/nimble_csv#53]
I've started to use NimbleCSV recently and using the `define/2` function is very restrictive. Right now the defined module will only be able to do what NimbleCSV insert there, and I won't be able to add more functions to that module.
That's why I think working with `use NimbleCSV, opts` would be better. If you agree I can start working on making it support both.

**Comment by josevalim** [comment]
I am quite keen in the current approach where the module is closed. So in your case I suggest to have a module that wraps the NimbleCSV module and delegates the relevant functions. :)  Thanks!
