### ISSUE TITLE
Escape only strings with leading zeros

### ISSUE THREAD

**Issue by patatoid** [dashbitco/nimble_csv#62]
Hi,

Wanted to generate a CSV file where common spreadsheet tools interpret strings like `"001"` as strings, not numbers. One way to do that is to escape that cell. Tried to add `0` as reserved characters do not meet my needs as I don't want to escape other cells with `0` which are numbers.

Do you think there is a way to achieve the escaping of cells with leading zeros ?

**Comment by josevalim** [comment]
You will have to transform the data before dumping it to NimbleCSV - as we simply encode the data as is. So for example, convert the numbers explicitly to strings or escape them with additional zeros yourself. :)
