### ISSUE TITLE
newlines failing only with Streams 

### ISSUE THREAD

**Issue by jeregrine** [dashbitco/nimble_csv#75]
I have found a strange CSV with `\r` as the newline separator in the wild that fails to parse when using `parse_stream`, but seems to work with `parse_string`. 

I attempted a fix but I had some trouble following the logic/macros. 

(aside)
While trying to narrow down a smaller csv test case I *struggled*. I don't know if I'm dumb at using Sed but every time I did a `sed -i 's/\r/\n/g' /tmp/mprop.csv` then `head /tmp/mprop.csv > /tmp/mprop-smol.csv` then `sed -i 's/\n/\r/g' /tmp/mprop-smol.csv` it would produce different file line endings than the original. Same with with elixir and String.replace. I am probably very tired and doing something wrong and dumb or maybe its a special secret \r that I cannot reproduce.
(/aside)

Anyways here is the test case, the data is public and ~90mb csv so this should give you a case to work with. 

```elixir
Mix.install([
  {:req, "~> 0.3.6"},
  {:nimble_csv, "~> 1.2"},
])

mprop_file = "/tmp/mprop.csv"
unless File.exists?(mprop_file) do
  # public data feel free to run this
  Req.get!("https://data.milwaukee.gov/dataset/562ab824-48a5-42cd-b714-87e205e489ba/resource/0a2c7f31-cd15-4151-8222-09dd57d5f16d/download/mprop.csv", output: mprop_file)
end

NimbleCSV.define(CSV, newlines: ["\r"])

File.read!("/tmp/mprop.csv")
|> CSV.parse_string()
|> Enum.take(1) 

# Slow but succeeds.

File.stream!("/tmp/mprop.csv", read_ahead: 100_000)
|> CSV.parse_stream()
|> Enum.take(1) 

# Errors ** (NimbleCSV.ParseError) unexpected escape character " in "MAP_EXT\"\r\"0000005005\",\"\",\"2022\",\"....
```

**Comment by josevalim** [comment]
Yes, it makes sense. `File.stream!` is line based (and afaik not configurable).

**Comment by josevalim** [comment]
Yes, but the stream in NimbleCSV expects to receive lines separate by newlines. I don't think we can stream by "\r".

**Comment by jeregrine** [comment]
Sounds good, thanks for your patience with me. <e
