### ISSUE TITLE
Dialyzer error in newlines_separator!

### ISSUE THREAD

**Issue by Munksgaard** [dashbitco/nimble_csv#80]
When running dialyzer in my project (which relies on nimble_csv), I get the following error:

```
deps/nimble_csv/lib/nimble_csv.ex:523:unmatched_return
The expression produces a value of type:

[integer(), ...]

but this value is unmatched.
```

By adding dialyzer to this repo with the following settings, I can confirm that the problem is in nimble_csv:

```elixir
dialyzer: [
  flags: [:unmatched_returns, :error_handling, :extra_return, :missing_return, :underspecs],
  plt_file: {:no_warn, "priv/plts/nimble_csv.plt"},
  plt_core_path: "priv/plts/core.plt",
]
```

While the error points at [this line](https://github.com/dashbitco/nimble_csv/blob/3b2e2f7f2a8bab5489a93a1e9a4e326d304c3134/lib/nimble_csv.ex#L534), it's clear the the missing match occurs somewhere within [`newlines_separator!`](https://github.com/dashbitco/nimble_csv/blob/3b2e2f7f2a8bab5489a93a1e9a4e326d304c3134/lib/nimble_csv.ex#L467-L491).

**Comment by josevalim** [comment]
We don't use dialyzer in this project, but a PR is welcome if you want to address the issue. Maybe adding `quote generated: true do` to some of the code generation will address it.
